### ISSUE TITLE
Suggest a better name to the package please if you could

### ISSUE THREAD

**Issue by saadshahd** [eventtus/react-redux-thunk-rest-api#3]
Please help me picking a suitable name for this package

The purpose of this package to find an organized mechanism to create actions from rest APIs

API beta: 

Start using this package by creating a single instance of the API object through calling `createApi`

**Comment by saadshahd** [comment]
restux as `re` from react, `st` from `rest`, ux from `redux`

**Comment by Muhnad** [comment]
react- phosphene || react- aglet || react- vela || react- divert || react- solace || react- amuse

**Comment by saadshahd** [comment]
@Muhnad random?

**Comment by Muhnad** [comment]
no, it's meaningful names.

**Comment by saadshahd** [comment]
react-estux

**Comment by maxios** [comment]
RestAct .. The rest of act.

**Comment by saadshahd** [comment]
Thank you @maxios
